### ISSUE TITLE
Download latest stable version yields some kind of preview

### ISSUE THREAD

**Issue by frank-e** [github/gitscm-old#1]
On https://code.google.com/hosting/settings (google code account settings for all google code users) there is a link to http://git-scm.com/downloads.  The target page announces a latest stable release 1.8.1.2 with release notes created 2013-01-28.  Clicking on http://git-scm.com/download/win yields a browser confirmation request to download a file "Git-1.8.1.2-preview.exe".  I refused to download the preview instead of the expected release.

**Comment by ben** [comment]
## tl;dr

That actually _is_ a released installer, but the naming convention is unfortunate. Sorry for the confusion.

## Walkthrough

If you stop the automatic download and click this link:

![Git - Downloading Package](https://f.cloud.github.com/assets/39902/129166/7cd5c5b2-6fd2-11e2-8ae7-4108ba77788b.jpg)

... and then this link:

![Git for Windows-2](https://f.cloud.github.com/assets/39902/129177/c7e6c3f8-6fd2-11e2-9be9-33d5dac2ab46.jpg)

You'll see that `Git-1.8.1.2-preview20130201.exe` is described as:

> Full installer for official Git for Windows 1.8.1.2
